server:
  port: ${SERVER_PORT:9010} # Порт сервера
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
spring:
  application:
    name: entera-office-booking
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://pg:5432/entera_office_booking?characterEncoding=UTF8}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: public
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: debug
entera:
  mail:
    email-sender: ${EMAIL_SENDER:dabuzarov@entera.pro}
  messaging:
    message-sender:
      exchange:
        name: "x.message-sender"
      routing-key: "process"
      queue:
        name: "q.message-sender.process"
